source $HOME/.config/env_vars

fpath=(~/.config/zsh $fpath)
autoload -Uz compinit && compinit -i

# set some important options (as early as possible)
# append history list to the history file; this is the default but we make sure
# because it's required for share_history.
setopt append_history
# save each command's beginning timestamp and the duration to the history file
setopt extended_history
# remove command lines from the history list when the first character on the
# line is a space
setopt histignorespace
# if a command is issued that can't be executed as a normal command, and the
# command is the name of a directory, perform the cd command to that directory.
setopt auto_cd
# in order to use #, ~ and ^ for filename generation grep word
# *~(*.gz|*.bz|*.bz2|*.zip|*.Z) -> searches for word not in compressed files
# don't forget to quote '^', '~' and '#'!
setopt extended_glob
# display PID when suspending processes as well
setopt longlistjobs
# report the status of backgrounds jobs immediately
setopt notify
# whenever a command completion is attempted, make sure the entire command path
# is hashed first.
setopt hash_list_all
# not just at the end
setopt completeinword
# Don't send SIGHUP to background processes when the shell exits.
setopt nohup
# make cd push the old directory onto the directory stack.
setopt auto_pushd
# avoid "beep"ing
setopt nobeep
# don't push the same dir twice.
setopt pushd_ignore_dups
# * shouldn't match dotfiles. ever.
setopt noglobdots
# use zsh style word splitting
setopt noshwordsplit
# don't error out when unset parameters are used
setopt unset
#
# alieases
alias vi="command nvim ${nvim_options:+${nvim_options[*]}}"
alias vim="command nvim ${nvim_options:+${nvim_options[*]}}"
alias wiki="nvim -c VimwikiIndex"

alias cat="command bat ${bat_options:+${bat_options[*]}}"
alias cal="command task calendar ${cal_options:+${cal_options[*]}}"

alias glow="command glow -l ${glow_options:+${glow_options[*]}}"

# ls
# Colors on GNU ls(1)
if ls --color=auto / >/dev/null 2>&1; then
    ls_options+=( --color=auto )
# Colors on FreeBSD and OSX ls(1)
elif ls -G / >/dev/null 2>&1; then
    ls_options+=( -G )
fi

alias ls="command ls ${ls_options:+${ls_options[*]}}"
alias la="command ls -la ${ls_options:+${ls_options[*]}}"
alias ll="command ls -l ${ls_options:+${ls_options[*]}}"
alias lh="command ls -hAl ${ls_options:+${ls_options[*]}}"
alias l="command ls -l ${ls_options:+${ls_options[*]}}"

# Pacman candy
alias pac-install="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias pac-remove="pacman -Qqe | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
alias pac-info="pacman -Qq | fzf --multi --preview 'bat <(pacman -Qi {1}) <(pacman -Fl {1} | awk \"{print \$2}\")'"

alias paru="command paru --assume-installed cargo ${glow_options:+${glow_options[*]}}"
alias aur-install="paru -Slq --aur | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru --assume-installed cargo -S"

#
# Podman
#
#
alias docker="podman ${podman_options:+${podman_options[*]}}"

podman() {
    if [[ $1 == "run" ]]; then
        shift
        command podman run --rm ${podman_options:+${podman_options[@]}} "$@"
    else
        command podman "$@"
    fi
}
#
# Misc
#

setopt vi # sets vi-mode

#
# fzf configs
#

FZF_DEFAULT_COMMAND='fd --type file --color=always --follow --hidden --exclude .git --exclude .cache'

FZF_DEFAULT_OPTS='--ansi '
FZF_DEFAULT_OPTS+='--inline-info '
FZF_DEFAULT_OPTS+='--cycle '
FZF_DEFAULT_OPTS+='--reverse '
FZF_DEFAULT_OPTS+='--preview-window=hidden --preview="bat --color always {}" --bind "ctrl-v:toggle-preview" '

export FZF_DEFAULT_OPTS

FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

stty -ixon

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

eval "$(starship init zsh)"
