[alacritty]
depends = ["graphics"]

[alacritty.files]
"configs/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[bat.files]
"configs/bat" = "~/.config/bat/config"

[secureboot.files]
"setup/secure-boot/80-secureboot.hook" = { target = "/etc/pacman.d/hooks/80-secureboot.hook", type = "template", owner = "root" }

[bin.files]
bin = { target = "~/.local/bin", type = "symbolic", recurse = false }

[cargo.files]
"configs/cargo.toml" = "~/.config/cargo/config.toml"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[tig.files]
"configs/tig" = "~/.config/tig/config"

[zsh.files]
"configs/zshrc" = "~/.zshrc.local"

[zellij]
depends = ["graphics"]

[zellij.files]
"zellij" = "~/.config/zellij"

[pacman.files]
"configs/pacman" = { target = "/etc/pacman.conf", type = "template", owner = "root" }

[makepkg.files]
"configs/makepkg" = { target = "/etc/makepkg.conf", type = "template", owner = "root" }

[paru.files]
"configs/paru" = { target = "/etc/paru.conf", type = "template", owner = "root" }
