[alacritty]
depends = ["graphics"]

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[bat.files]
"bat" = "~/.config/bat/config"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[tig.files]
"tig" = "~/.config/tig/config"

[zsh.files]
"zshrc" = "~/.zshrc.local"

[zellij]
depends = ["graphics"]

[zellij.files]
"zellij" = "~/.config/zellij"
