[base]
depends = ["graphics"]

[base.files]
"base/bat" = "~/.config/bat/config"
"base/zshrc" = "~/.zshrc.local"
"base/zellij" = "~/.config/zellij"
"base/bin" = { target = "~/.local/bin", type = "symbolic", recurse = false }

[developer.files]
"developer/tig" = "~/.config/tig/config"
"developer/git" = "~/.config/git/config"
"developer/cargo.toml" = "~/.config/cargo/config.toml"
"developer/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[desktop]
depends = ["graphics"]

[desktop.files]
"desktop/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[system.files]
"system/pacman" = { target = "/etc/pacman.conf", type = "template", owner = "root" }
"system/makepkg" = { target = "/etc/makepkg.conf", type = "template", owner = "root" }
"system/paru" = { target = "/etc/paru.conf", type = "template", owner = "root" }

[secureboot.files]
"setup/secure-boot/80-secureboot.hook" = { target = "/etc/pacman.d/hooks/80-secureboot.hook", type = "template", owner = "root" }

