[alacritty]
depends = ["graphics"]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[bat.files]
"bat" = "~/.config/bat/config"

[tig.files]
"tig" = "~/.config/tig/config"

[zellij]
depends = ["graphics"]

[zellij.files]
"zellij" = "~/.config/zellij"
