###############################################################################
# Base
###############################################################################
[base]
depends = ["graphics"]

[base.files]
"base/install.sh" = "./.install/01_base"
"base/bat" = "~/.config/bat/config"
"base/env_vars" = "~/.config/env_vars"
"base/bashrc" = "~/.bashrc"
"base/bash_profile" = "~/.bash_profile"
"base/zshrc" = "~/.zshrc.local"
"base/zellij" = "~/.config/zellij"
"base/bin" = { target = "~/.local/bin", type = "symbolic", recurse = false }

###############################################################################
# Developer
###############################################################################
[developer]
depends = ["rust"]

[developer.files]
"developer/install.sh" = "./.install/02_developer"
"developer/tig" = "~/.config/tig/config"
"developer/git" = "~/.config/git/config"
"developer/cargo.toml" = "~/.config/cargo/config.toml"
"developer/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

###############################################################################
# Desktop
###############################################################################
[desktop]
depends = ["graphics"]

[desktop.files]
"desktop/install.sh" = "./.install/03_desktop"
# Gtk and qt
"desktop/gtk_qt/gtkrc-2.0" = "~/.config/gtk-2.0/settings.ini"
"desktop/gtk_qt/gtkrc-3.0" = "~/.config/gtk-3.0/settings.ini"
"desktop/gtk_qt/qt6ct" = "~/.config/qt6ct/qt6ct.conf"
"desktop/gtk_qt/qt5ct" = "~/.config/qt5ct/qt5ct.conf"
"desktop/gtk_qt/xsettingsd" = "~/.config/xsettingsd/xsettingsd.conf"
# alacritty
"desktop/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
# Fonts
"desktop/fonts/fonts.conf" = "~/.config/fontconfig/fonts.conf"
"desktop/fonts/freetype2.sh" = { target = "/etc/profile.d/freetype2.sh", type = "template", owner = "root" }
# Firefox
"desktop/firefox/autoconfig.js" = { target = "/usr/lib/firefox/defaults/pref/autoconfig.js", type = "template", owner = "root" }
"desktop/firefox/mozilla.cfg" = { target = "/usr/lib/firefox/mozilla.cfg", type = "template", owner = "root" }
"desktop/firefox/policies.json" = { target = "/etc/firefox/policies/policies.json", type = "template", owner = "root" }

###############################################################################
# Hyprland
###############################################################################
[hyprland]
depends = ["graphics"]

[hyprland.files]
"hyprland/install.sh" = "./.install/04_hyprland"
"hyprland/hyprland" = "~/.config/hypr/hyprland.conf"
"hyprland/hypridle" = "~/.config/hypr/hypridle.conf"
"hyprland/hyprlock" = "~/.config/hypr/hyprlock.conf"
"hyprland/hyprpaper" = "~/.config/hypr/hyprpaper.conf"
"hyprland/waybar" = "~/.config/waybar"
"hyprland/wofi" = "~/.config/wofi"

###############################################################################
# System
###############################################################################
[system.files]
"system/install.sh" = "./.install/00_system"
"system/pacman" = { target = "/etc/pacman.conf", type = "template", owner = "root" }
"system/makepkg" = { target = "/etc/makepkg.conf", type = "template", owner = "root" }
"system/paru" = { target = "/etc/paru.conf", type = "template", owner = "root" }
"system/ssh/20-base_client_hardening" = { target = "/etc/ssh/ssh_config.d/20-base_client_hardening.conf", type = "template", owner = "root" }
"system/ssh/20-base_server_hardening" = { target = "/etc/ssh/sshd_config.d/20-base_server_hardening.conf", type = "template", owner = "root" }

###############################################################################
# Secure Boot
###############################################################################
[secureboot.files]
"setup/secure-boot/80-secureboot.hook" = { target = "/etc/pacman.d/hooks/80-secureboot.hook", type = "template", owner = "root" }
