[alacritty]
depends = ["graphics"]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[bat.files]
"bat" = "~/.config/bat/config"

[nvim.files]
"nvim" = "~/.config/nvim"

[tig.files]
"tig" = "~/.config/tig/config"

[zsh.files]
"zshrc" = "~/.zshrc.local"

[zellij]
depends = ["graphics"]

[zellij.files]
"zellij" = "~/.config/zellij"
