includes = ["./.dotter/graphics.toml"]

packages = [
  "alacritty",
  "bat",
  "bin",
  "secureboot",
  "nvim",
  "cargo",
  "tig",
  "zsh",
  "zellij",
  "pacman",
  "makepkg",
]

[variables]
font_size = 10
font_family = "Hack Nerd Font"
cpu_cores = 8
