includes = [
  "./.dotter/graphics.toml",
  "./.dotter/rust.toml"
 ]

packages = [
  "base",
  "developer",
  "system",
  "desktop",
  "hyprland",
]

[variables]
font_size = 10
font_family = "Noto"
font_mono = "Hack Nerd Font"
cpu_cores = 4
