includes = [
  "./.dotter/graphics.toml",
  "./.dotter/rust.toml"
 ]

packages = [
  "base",
  "developer",
  "system",
  "desktop",
]

[variables]
font_size = 10
font_family = "Hack Nerd Font"
cpu_cores = 8
