#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m'

system=$1

echo -e "${GREEN}>>> Installing paru for AUR${NC}"
./setup/paru

echo -e "${GREEN}>>> Installing Basic packages${NC}"
./setup/base

echo -e "${GREEN}>>> Installing AUR packages${NC}"
./setup/aur

echo -e "${GREEN}>>> Installing Rust${NC}"
./setup/rust

case $system in
    desktop)
        echo -e "${GREEN}>>> Installing packages for Desktop/Laptop ${NC}"
        ./setup/desktop
        ;;
esac

dotter
