#!/bin/bash

sudo pacman -S --noconfirm --needed \
  sccache \
  lld \
  clang

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup component add rust-analyzer
rustup component add clippy
rustup component add rustfmt
